export const DAYS = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
];

export const employee = {
  id: "1",
  name: "John",
  businessId: "1",
  department: "women",
  position: "cashier",
  minHours: 15,
  maxHours: 40,
  email: "",
  priority: 1,
};

export const availabilities = [
  {
    dayOfWeek: 0,
    start: "09:00",
    end: "14:00",
    id: "7",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "14:00",
    end: "17:00",
    id: "1",
    userId: "1",
  },
  {
    dayOfWeek: 2,
    start: "12:00",
    end: "17:00",
    id: "2",
    userId: "1",
  },
  {
    dayOfWeek: 3,
    start: "09:00",
    end: "17:00",
    id: "3",
    userId: "1",
  },
  {
    dayOfWeek: 4,
    start: "09:00",
    end: "10:00",
    id: "4",
    userId: "1",
  },
  {
    dayOfWeek: 5,
    start: "09:00",
    end: "11:00",
    id: "5",
    userId: "1",
  },
  {
    dayOfWeek: 6,
    start: "10:00",
    end: "17:00",
    id: "6",
    userId: "1",
  },
];

export const availabilitiesForDayOfWeek = [
  {
    dayOfWeek: 1,
    start: "09:00",
    end: "14:00",
    id: "7",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "14:00",
    end: "17:00",
    id: "1",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "12:00",
    end: "17:00",
    id: "2",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "09:00",
    end: "17:00",
    id: "3",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "09:00",
    end: "10:00",
    id: "4",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "09:00",
    end: "11:00",
    id: "5",
    userId: "1",
  },
  {
    dayOfWeek: 1,
    start: "10:00",
    end: "17:00",
    id: "6",
    userId: "1",
  },
];

export const constraints = [
  {
    id: "1",
    dayOfWeek: 1,
    start: "09:00",
    end: "12:00",
    type: "MAX" as const,
    businessId: "1",
    constraint: 4,
    department: "men",
    position: "cashier",
  },
  {
    id: "2",
    dayOfWeek: 1,
    start: "12:00",
    end: "14:00",
    type: "EXACT" as const,
    businessId: "1",
    constraint: 4,
    department: "women",
    position: "cashier",
  },
  {
    id: "3",
    dayOfWeek: 1,
    start: "14:00",
    end: "17:00",
    type: "MIN" as const,
    businessId: "1",
    constraint: 4,
    department: "women",
    position: "cashier",
  },
  {
    id: "4",
    department: "women",
    position: "cashier",
    dayOfWeek: 1,
    start: "09:00",
    end: "12:00",
    type: "MAX" as const,
    businessId: "1",
    constraint: 4,
  },
  {
    id: "5",
    department: "women",
    position: "cashier",
    dayOfWeek: 2,
    start: "12:00",
    end: "14:00",
    type: "MAX" as const,
    businessId: "1",
    constraint: 4,
  },
];

export const shifts = [
  {
    id: "1",
    date: "2021-01-04",
    start: "09:00",
    end: "14:00",
    userId: "1",
    businessId: "1",
    user: employee,
  },
  {
    id: "2",
    date: "2021-01-01",
    start: "14:00",
    end: "17:00",
    userId: "1",
    businessId: "1",
    user: employee,
  },
  {
    id: "3",
    date: "2021-01-01",
    start: "12:00",
    end: "17:00",
    userId: "1",
    businessId: "1",
    user: employee,
  },
];
