-- AlterTable
ALTER TABLE "User" ADD COLUMN     "endingHours" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "maxHours" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minHours" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "startingHours" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
